symbols = list(input())
print("---------")
print(f"| {' '.join(map(str, symbols[0:3]))} |")
print(f"| {' '.join(map(str, symbols[3:6]))} |")
print(f"| {' '.join(map(str, symbols[6:9]))} |")
print("---------")
